[package]
name = "sharppy"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full", "process"] }
anyhow = "1.0"
pretty_env_logger = "0.5"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
